---
version: '3.7'

services:
  webtop:
    image: quay.io/linuxserver.io/webtop:ubuntu-mate
    container_name: webtop2
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - TITLE=Webtop_Docker #optional
    volumes:
      - /home/andy/webtop_docker:/config
    ports:
      - 4000:3000
      - 4001:3001
    shm_size: "2gb" #optional
    restart: unless-stopped
    privileged: true