version: '3.1'

services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
    - /home/andy/heimdall:/config
    ports:
      - 8090:80
      - 8091:443
    restart: unless-stopped
