# postgres/example

version: '3.1'

services:

  app:
    image: nextcloud
    restart: always
    hostname: nextcloud
    container_name: nextcloud
    ports:
      - 8081:80
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    volumes:
      - data:/var/www/html

volumes:
  data:
    driver: local