# ppostgres/example

version: '3.1'

services:

  db:
    image: postgres
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
    volumes:
      - db:/var/lib/postgresql/data

  app:
    image: nextcloud
    restart: always
    hostname: nextcloud
    container_name: nextcloud
    ports:
      - 8081:80
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
    volumes:
      - nextcloud:/var/www/html

volumes:
  db:
    driver: local
  nextcloud:
    driver: local