# ppostgres/example

version: '3.1'

services:

  db:
    image: postgres
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=secretdb
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    hostname: adminer
    container_name: adminer
    ports:
      - 8080:8080

volumes:
  db:
    driver: local